language: node_js

node_js:
  - 'stable'
  - '8'
  - '6'

sudo: false  

matrix:
  fast_finish: true

branches:
  only: 
    - master
    - develop

cache:
  directories:
    - "node_modules"

git:
  depth: 1